#!/usr/bin/env ansible-playbook

- name: Gather prerequisites
  hosts: all
  gather_facts: True
  tasks:
    - name: create groups based on distribution
      group_by: key={{ ansible_distribution }}

- name: Configure the MySQL Partition
  hosts: Ubuntu
  become: True
  vars:
       user_account: "root"
       device_name: "/dev/sdb"
       group_name: "mysql"
       volume_name: "storage"
       volume_size: "7G"
       mount_point: "/var/lib/mysql"
       guard_prefix: "ansible-mysql-"
       pvcreate_guard: "/var/{{ guard_prefix }}-pvcreate"
       vgcreate_guard: "/var/{{ guard_prefix }}-vgcreate"
       lvcreate_guard: "/var/{{ guard_prefix }}-lvcreate"
       mkfs_guard: "/var/{{ guard_prefix }}-mkfs"
  tasks:
      - apt: name=lvm2 state=present update_cache=true cache_valid_time=3600 install_recommends=true
      - command: /sbin/pvcreate {{ device_name }} creates={{ pvcreate_guard }}
      - file: path={{ pvcreate_guard }} state=touch
      - command: /sbin/vgcreate {{ group_name }} {{ device_name }} creates={{ vgcreate_guard }}
      - file: path={{ vgcreate_guard }} state=touch
      - command: /sbin/lvcreate --name {{ volume_name }} --size {{ volume_size }} {{ group_name }} creates={{ lvcreate_guard }}
      - file: path={{ lvcreate_guard }} state=touch
      - command: /sbin/mkfs.ext4 /dev/{{ group_name }}/{{ volume_name }} creates={{ mkfs_guard }}
      - file: path={{ mkfs_guard }} state=touch
      - command: /bin/mkdir --parents {{ mount_point }}
      - lineinfile: dest=/etc/fstab line="/dev/{{ group_name }}/{{ volume_name }} {{ mount_point }} ext4 defaults 0 0"
      - file: path={{ mount_point }} owner={{ user_account }} group={{ user_account }} recurse=true state=directory
      - command: /bin/mount -a

- name: Configure the RabbitMQ Partition
  hosts: Ubuntu
  become: True
  vars:
       user_account: "root"
       device_name: "/dev/sdb"
       group_name: "rabbitmq"
       volume_name: "storage"
       volume_size: "7G"
       mount_point: "/var/lib/rabbitmq"
       guard_prefix: "ansible-rabbitm1-"
       pvcreate_guard: "/var/{{ guard_prefix }}-pvcreate"
       vgcreate_guard: "/var/{{ guard_prefix }}-vgcreate"
       lvcreate_guard: "/var/{{ guard_prefix }}-lvcreate"
       mkfs_guard: "/var/{{ guard_prefix }}-mkfs"
  tasks:
      - apt: name=lvm2 state=present update_cache=true cache_valid_time=3600 install_recommends=true
      - command: /sbin/pvcreate {{ device_name }} creates={{ pvcreate_guard }}
      - file: path={{ pvcreate_guard }} state=touch
      - command: /sbin/vgcreate {{ group_name }} {{ device_name }} creates={{ vgcreate_guard }}
      - file: path={{ vgcreate_guard }} state=touch
      - command: /sbin/lvcreate --name {{ volume_name }} --size {{ volume_size }} {{ group_name }} creates={{ lvcreate_guard }}
      - file: path={{ lvcreate_guard }} state=touch
      - command: /sbin/mkfs.ext4 /dev/{{ group_name }}/{{ volume_name }} creates={{ mkfs_guard }}
      - file: path={{ mkfs_guard }} state=touch
      - command: /bin/mkdir --parents {{ mount_point }}
      - lineinfile: dest=/etc/fstab line="/dev/{{ group_name }}/{{ volume_name }} {{ mount_point }} ext4 defaults 0 0"
      - file: path={{ mount_point }} owner={{ user_account }} group={{ user_account }} recurse=true state=directory
      - command: /bin/mount -a


